# Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [3]:
import numpy as np
a = np.array([3, 5])
b = np.array([2, 5])
print("Lists are:")
print(a)
print(b)
print("Comparison - greater")
print(np.greater(a, b))
print("Comparison - greater_equal")
print(np.greater_equal(a, b))
print("Comparison - less")
print(np.less(a, b))
print("Comparison - less_equal")
print(np.less_equal(a, b))

Lists are:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [4]:
import numpy as np
arr=np.zeros(10)
print("10 zeros:")
print(arr)
arr=np.ones(10)
print("10 ones:")
print(arr)
arr=np.ones(10)*5
print("10 fives:")
print(arr)

10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [6]:
import numpy as np
arr=np.eye(3,3)
print("array is:")
print(arr)
print("Sum of all elements:")
print(np.sum(arr))
print("Sum of each column:")
print(np.sum(arr, axis=0))
print("Sum of each row:")
print(np.sum(arr, axis=1))



array is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Sum of all elements:
3.0
Sum of each column:
[1. 1. 1.]
Sum of each row:
[1. 1. 1.]


# Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [9]:
import numpy as np
s1=10
s2=5
print("add=",np.add(s1,s2))
print("sub=",np.subtract(s1,s2))
print("mul=",np.multiply(s1,s2))
print("div=",np.divide(s1,s2))

add= 15
sub= 5
mul= 50
div= 2.0


# Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [10]:
from scipy import linalg
d=np.mat([[3,4],[5,6]])
linalg.sinm(d)
linalg.cosm(d)
linalg.tanm(d)


array([[-0.21717737,  0.00408362],
       [ 0.00510453, -0.21411465]])

In [11]:
import numpy as np
print("sine:angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine:angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent:angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine:angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine:angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent:angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [13]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Madhu', 'Nive', 'Sandy'],
        'score': [12.5, 9, np.nan],
        'attempts': [1, 3, 2],
        'qualify': ['no', 'yes', 'yes']}
labels = ['a', 'b', 'c']

df = pd.DataFrame(exam_data , index=labels)
print(df)

    name  score  attempts qualify
a  Madhu   12.5         1      no
b   Nive    9.0         3     yes
c  Sandy    NaN         2     yes


# Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [15]:
print(df[['name','score']])

    name  score
a  Madhu   12.5
b   Nive    9.0
c  Sandy    NaN


# Write a Pandas program to join the two given dataframes along rows and assign all data.

In [19]:
import pandas as pd

exam_data  = pd.DataFrame({'name': ['Madhu', 'Nive', 'Sandy'],
        'score': [12.5, 9,6],
        'attempts': [1, 3, 2],
        'qualify': ['no', 'yes', 'yes']})
exam_data2  =pd.DataFrame({'name': ['uma', 'Nithin', 'Santhosh'],
        'score': [12, 9.2,6.8],
        'attempts': [3, 2, 1],
        'qualify': ['yes', 'yes', 'yes']})
result=pd.concat([exam_data, exam_data2])
print(result)

       name  score  attempts qualify
0     Madhu   12.5         1      no
1      Nive    9.0         3     yes
2     Sandy    6.0         2     yes
0       uma   12.0         3     yes
1    Nithin    9.2         2     yes
2  Santhosh    6.8         1     yes


# Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [20]:
import pandas as pd
import numpy as np

exam_data  = pd.DataFrame({'name': ['Madhu', 'Nive', 'Sandy'],
        'score': [12.5, 9,np.nan],
        'attempts': [1, np.nan, 2],
        'qualify': ['no', 'yes', 'yes']})
print(exam_data.isna())
                    

    name  score  attempts  qualify
0  False  False     False    False
1  False  False      True    False
2  False   True     False    False


# Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [22]:
# import pandas as pd
arr = pd.Series([3,6,9,12,1])
print(arr)

0     3
1     6
2     9
3    12
4     1
dtype: int64


#                                              THANK YOU!!!!!!